# Generated by Django 5.1.3 on 2024-11-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('content', models.TextField(verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Prompt do professor',
                'verbose_name_plural': 'Prompts do professor',
            },
        ),
    ]
