# Generated by Django 5.1.3 on 2024-11-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishbot', '0003_student_about_student_age_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='chat_id do Telegram'),
        ),
    ]
